'use client';
import {useEffect,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
const levels=["3ème année collège","Tronc Commun","1ère année Bac","2ème année Bac"];
const tabs=[["home","🏠","Vue d'ensemble"],["students","👨‍🎓","Élèves"],["teachers","👨‍🏫","Professeurs"],["subjects","📚","Matières"],["schedule","🗓️","Emploi du temps"],["qr","📱","QR & Présence"],["payments","💰","Paiements"],["news","📢","Annonces"],["stats","📊","Statistiques"]];
const id=()=>Math.random().toString(36).slice(2);
const load=(k:string)=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}};
export default function Admin(){
 const [tab,setTab]=useState("home"),[ready,setReady]=useState(false);
 const [students,setStudents]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[schedule,setSchedule]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[news,setNews]=useState<any[]>([]),[presence,setPresence]=useState<any[]>([]),[selected,setSelected]=useState<any>(null);
 useEffect(()=>{setStudents(load("students"));setTeachers(load("teachers"));setSubjects(load("subjects"));setSchedule(load("schedule"));setPayments(load("payments"));setNews(load("news"));setPresence(load("presence"));setReady(true)},[]);
 useEffect(()=>{if(ready){localStorage.setItem("students",JSON.stringify(students));localStorage.setItem("teachers",JSON.stringify(teachers));localStorage.setItem("subjects",JSON.stringify(subjects));localStorage.setItem("schedule",JSON.stringify(schedule));localStorage.setItem("payments",JSON.stringify(payments));localStorage.setItem("news",JSON.stringify(news));localStorage.setItem("presence",JSON.stringify(presence));}},[students,teachers,subjects,schedule,payments,news,presence,ready]);
 const del=(set:any,arr:any[],x:string)=>set(arr.filter((a:any)=>a.id!==x));
 const add=(e:any,set:any,arr:any[],type:string)=>{e.preventDefault();let f=new FormData(e.currentTarget),o:any={id:id()};f.forEach((v,k)=>o[k]=v);if(type==="student")o.code="CLP-"+Date.now().toString().slice(-6);set([...arr,o]);e.currentTarget.reset()};
 const mark=(status:string)=>{if(!selected)return;let date=new Date().toISOString().slice(0,10);setPresence([...presence.filter((p:any)=>!(p.student===selected.id&&p.date===date)),{id:id(),student:selected.id,date,status}])};
 if(!ready)return <div className="loading">Chargement...</div>;
 const today=new Date().toISOString().slice(0,10), present=presence.filter((p:any)=>p.date===today&&p.status==="Présent").length;
 const Form=({children,onSubmit}:any)=><form className="form" onSubmit={onSubmit}>{children}</form>;
 return <main className="dash"><aside><a className="logo" href="/"><img src="/logo.jpeg"/><span>Centre<br/><b>Les Profs</b></span></a>{tabs.map(t=><button className={tab===t[0]?"active":""} onClick={()=>setTab(t[0])} key={t[0]}><i>{t[1]}</i><span>{t[2]}</span></button>)}<a className="public" href="/">↗ Site public</a></aside>
 <section className="content"><div className="top"><div><p className="tag">ADMINISTRATION</p><h1>{tabs.find(x=>x[0]===tab)?.[2]}</h1></div><b>🔴 Admin</b></div>
 {tab==="home"&&<><div className="metrics"><Metric i="👨‍🎓" n={students.length} t="Élèves"/><Metric i="👨‍🏫" n={teachers.length} t="Professeurs"/><Metric i="📚" n={subjects.length} t="Matières"/><Metric i="✅" n={present} t="Présents aujourd'hui"/></div><Box title="Bienvenue"><p>Gère ton centre depuis un seul endroit. Commence par ajouter les élèves, les professeurs et les matières.</p></Box></>}
 {tab==="students"&&<div className="cols"><Box title="Ajouter un élève"><Form onSubmit={(e:any)=>add(e,setStudents,students,"student")}><input name="name" placeholder="Nom complet" required/><input name="phone" placeholder="Téléphone"/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter</button></Form></Box><Box title={"Liste des élèves ("+students.length+")"}>{students.map(s=><Row key={s.id} title={s.name} sub={s.level+" • "+(s.phone||"")} action={()=>del(setStudents,students,s.id)}/>)||null}{!students.length&&<p className="empty">Aucun élève.</p>}</Box></div>}
 {tab==="teachers"&&<div className="cols"><Box title="Ajouter un professeur"><Form onSubmit={(e:any)=>add(e,setTeachers,teachers,"teacher")}><input name="name" placeholder="Nom complet" required/><input name="subject" placeholder="Matière"/><input name="phone" placeholder="Téléphone"/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter</button></Form></Box><Box title="Professeurs">{teachers.map(x=><Row key={x.id} title={x.name} sub={(x.subject||"")+" • "+x.level} action={()=>del(setTeachers,teachers,x.id)}/>)||null}{!teachers.length&&<p className="empty">Aucun professeur.</p>}</Box></div>}
 {tab==="subjects"&&<div className="cols"><Box title="Ajouter une matière"><Form onSubmit={(e:any)=>add(e,setSubjects,subjects,"subject")}><input name="name" placeholder="Nom de la matière" required/><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><button>Ajouter</button></Form></Box><Box title="Matières">{subjects.map(x=><Row key={x.id} title={x.name} sub={x.level} action={()=>del(setSubjects,subjects,x.id)}/>)||null}{!subjects.length&&<p className="empty">Aucune matière.</p>}</Box></div>}
 {tab==="schedule"&&<div className="cols"><Box title="Nouvelle séance"><Form onSubmit={(e:any)=>add(e,setSchedule,schedule,"schedule")}><select name="level">{levels.map(x=><option key={x}>{x}</option>)}</select><input name="subject" placeholder="Matière" required/><input name="teacher" placeholder="Professeur"/><input name="day" placeholder="Jour"/><input name="time" placeholder="Heure"/><button>Ajouter</button></Form></Box><Box title="Emploi du temps">{schedule.map(x=><Row key={x.id} title={x.subject+" — "+x.level} sub={(x.day||"")+" • "+(x.time||"")+" • "+(x.teacher||"")} action={()=>del(setSchedule,schedule,x.id)}/>)||null}{!schedule.length&&<p className="empty">Aucune séance.</p>}</Box></div>}
 {tab==="qr"&&<div className="cols"><Box title="Choisir un élève"><div className="selectList">{students.map(s=><button className="pick" onClick={()=>setSelected(s)} key={s.id}>{s.name}<small>{s.code}</small></button>)}</div>{!students.length&&<p className="empty">Ajoute des élèves d'abord.</p>}</Box><Box title={selected?selected.name:"QR Code & présence"}>{selected?<div className="qr"><QRCodeSVG value={selected.code} size={210}/><code>{selected.code}</code><div><button onClick={()=>mark("Présent")} className="green">✓ Présent</button><button onClick={()=>mark("Absent")} className="redbtn">✕ Absent</button><button onClick={()=>mark("Retard")} className="orange">⏱ Retard</button></div></div>:<p className="empty">Sélectionne un élève.</p>}</Box></div>}
 {tab==="payments"&&<div className="cols"><Box title="Ajouter un paiement"><Form onSubmit={(e:any)=>add(e,setPayments,payments,"payment")}><select name="student"><option>Choisir un élève</option>{students.map(s=><option key={s.id}>{s.name}</option>)}</select><input name="amount" type="number" placeholder="Montant DH" required/><select name="status"><option>Payé</option><option>En attente</option></select><button>Enregistrer</button></Form></Box><Box title="Paiements">{payments.map(x=><Row key={x.id} title={x.student} sub={x.amount+" DH • "+x.status} action={()=>del(setPayments,payments,x.id)}/>)||null}{!payments.length&&<p className="empty">Aucun paiement.</p>}</Box></div>}
 {tab==="news"&&<div className="cols"><Box title="Nouvelle annonce"><Form onSubmit={(e:any)=>add(e,setNews,news,"news")}><input name="title" placeholder="Titre" required/><textarea name="text" placeholder="Contenu" required/><button>Publier</button></Form></Box><Box title="Annonces">{news.map(x=><Row key={x.id} title={"📢 "+x.title} sub={x.text} action={()=>del(setNews,news,x.id)}/>)||null}{!news.length&&<p className="empty">Aucune annonce.</p>}</Box></div>}
 {tab==="stats"&&<><div className="metrics"><Metric i="👨‍🎓" n={students.length} t="Total élèves"/><Metric i="👨‍🏫" n={teachers.length} t="Total professeurs"/><Metric i="💰" n={payments.filter(x=>x.status==="Payé").length} t="Paiements payés"/><Metric i="🗓️" n={schedule.length} t="Séances"/></div><Box title="Répartition par niveau">{levels.map(x=><div className="stat" key={x}><span>{x}</span><b>{students.filter(s=>s.level===x).length} élèves</b></div>)}</Box></>}
 </section></main>}
function Box({title,children}:{title:string,children:any}){return <div className="box"><h2>{title}</h2>{children}</div>}
function Metric({i,n,t}:{i:string,n:number,t:string}){return <div className="metric"><i>{i}</i><div><b>{n}</b><small>{t}</small></div></div>}
function Row({title,sub,action}:{title:string,sub:string,action:()=>void}){return <div className="row"><div><b>{title}</b><small>{sub}</small></div><button className="delete" onClick={action}>Supprimer</button></div>}